ALTER TABLE users DROP CONSTRAINT IF EXISTS check_role;
ALTER TABLE users DROP CONSTRAINT IF EXISTS check_gender;
ALTER TABLE users DROP CONSTRAINT IF EXISTS check_zipcode;
ALTER TABLE users DROP CONSTRAINT IF EXISTS check_date_of_birth;
